<?xml version="1.0" encoding="UTF-8" standalone="yes"?><!DOCTYPE root [
<!ELEMENT root (resource+, path*, time_point*, time_profile*, routed_job*, job*, job_op*, setup_removal_table*, machine*, platform*, connection*)>
<!ELEMENT resource (id_resource, name, resource_type, info1*, info2*)>
<!ELEMENT id_resource (#PCDATA)>
<!ELEMENT resource_type (#PCDATA)>
<!ELEMENT info1 (#PCDATA)>
<!ELEMENT info2 (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT path (id_path, resource_list_elem+)>
<!ELEMENT resource_list_elem (id_resource)>
<!ELEMENT id_path (#PCDATA)>
<!ELEMENT time_point (id_time_point, processing_time*, perishability_time*,release_no_timeshift*, release_time*, due_date_no_timeshift*, due_date_time*, deadline_no_timeshift*, deadline_time*, weight_obj*, setup_time*, removal_time*, dependent_setup_type*, dependent_removal_type*, route_booking_forward*, route_booking_backward*)>
<!ELEMENT id_time_point (#PCDATA)>
<!ELEMENT processing_time (#PCDATA)>
<!ELEMENT perishability_time (#PCDATA)>
<!ELEMENT release_no_timeshift (#PCDATA)>
<!ELEMENT release_time (#PCDATA)>
<!ELEMENT due_date_no_timeshift (#PCDATA)>
<!ELEMENT due_date_time (#PCDATA)>
<!ELEMENT deadline_no_timeshift (#PCDATA)>
<!ELEMENT deadline_time (#PCDATA)>
<!ELEMENT weight_obj (#PCDATA)>
<!ELEMENT setup_time (#PCDATA)>
<!ELEMENT removal_time (#PCDATA)>
<!ELEMENT dependent_setup_type (#PCDATA)>
<!ELEMENT dependent_removal_type (#PCDATA)>
<!ELEMENT route_booking_forward (#PCDATA)>
<!ELEMENT route_booking_backward (#PCDATA)>
<!ELEMENT time_profile (id_time_profile, id_path, time_point_list_elem+)>
<!ELEMENT time_point_list_elem (id_time_point)>
<!ELEMENT id_time_profile (#PCDATA)>
<!ELEMENT routed_job (id_routed_job, job_type, time_shift, id_time_profile, weight_obj*)>
<!ELEMENT routed_job_list_elem (id_routed_job)>
<!ELEMENT job (id_job, name, routed_job_list_elem+, multiple_routings_list_elem+)>
<!ELEMENT multiple_routings_list_elem (id_resource, time_profile_list_elem+)>
<!ELEMENT time_profile_list_elem (id_time_profile)>
<!ELEMENT id_job (#PCDATA)>
<!ELEMENT id_routed_job (#PCDATA)>
<!ELEMENT job_type (#PCDATA)>
<!ELEMENT time_shift (#PCDATA)>
<!ELEMENT job_op (id_job, operation+)>
<!ELEMENT operation (id_resource, time_point)>
<!ELEMENT setup_removal_table (table_entry+)>
<!ELEMENT table_entry (dependent_type1, dependent_type2,  setup_removal_type, dependent_time)>
<!ELEMENT dependent_type1 (#PCDATA)>
<!ELEMENT dependent_type2 (#PCDATA)>
<!ELEMENT setup_removal_type (#PCDATA)>
<!ELEMENT dependent_time (#PCDATA)>
<!ELEMENT machine (resource_list_elem+)>
<!ELEMENT platform (resource_list_elem+)>
<!ELEMENT connection (id_job_from, id_resource_from, id_job_to, id_resource_to, connection_weight, connection_price, is_passenger)>
<!ELEMENT id_job_from (#PCDATA)>
<!ELEMENT id_resource_from (#PCDATA)>
<!ELEMENT id_job_to (#PCDATA)>
<!ELEMENT id_resource_to (#PCDATA)>
<!ELEMENT connection_weight (#PCDATA)>
<!ELEMENT connection_price (#PCDATA)>
<!ELEMENT is_passenger (#PCDATA)>]><root><resource><id_resource>970</id_resource><name>Streckengleis-920_1730</name><resource_type>corridor</resource_type></resource><resource><id_resource>539</id_resource><name>Streckengleis-003_2779</name><resource_type>corridor</resource_type></resource><resource><id_resource>257</id_resource><name>Streckengleis-501_1155</name><resource_type>corridor</resource_type></resource><resource><id_resource>1339</id_resource><name>Streckengleis-122_2032</name><resource_type>corridor</resource_type></resource><resource><id_resource>615</id_resource><name>Streckengleis-227_181</name><resource_type>corridor</resource_type></resource><resource><id_resource>673</id_resource><name>Streckengleis-13_101080056</name><resource_type>corridor</resource_type></resource><resource><id_resource>1172</id_resource><name>Streckengleis-162_2638</name><resource_type>corridor</resource_type></resource><resource><id_resource>64</id_resource><name>Streckengleis-711_29</name><resource_type>corridor</resource_type></resource><resource><id_resource>1154</id_resource><name>Hauptgleis-WD-131</name><resource_type>blocking</resource_type></resource><resource><id_resource>277</id_resource><name>Streckengleis-475_156</name><resource_type>corridor</resource_type></resource><resource><id_resource>469</id_resource><name>Streckengleis-595_99</name><resource_type>corridor</resource_type></resource><resource><id_resource>665</id_resource><name>Streckengleis-64_102026715</name><resource_type>corridor</resource_type></resource><resource><id_resource>746</id_resource><name>Streckengleis-461_2868</name><resource_type>corridor</resource_type></resource><resource><id_resource>1088</id_resource><name>Streckengleis-44_101078813</name><resource_type>corridor</resource_type></resource><resource><id_resource>636</id_resource><name>Streckengleis-274_1923</name><resource_type>corridor</resource_type></resource><resource><id_resource>1003</id_resource><name>Streckengleis-440_1642</name><resource_type>corridor</resource_type></resource><resource><id_resource>918</id_resource><name>Streckengleis-42_2987</name><resource_type>corridor</resource_type></resource><resource><id_resource>1002</id_resource><name>Streckengleis-440_1643</name><resource_type>corridor</resource_type></resource><resource><id_resource>1016</id_resource><name>Streckengleis-429_2075</name><resource_type>corridor</resource_type></resource><resource><id_resource>1303</id_resource><name>Streckengleis-R34_101084465</name><resource_type>corridor</resource_type></resource><resource><id_resource>1111</id_resource><name>Streckengleis-204_2715</name><resource_type>corridor</resource_type></resource><resource><id_resource>777</id_resource><name>Streckengleis-610_101032053</name><resource_type>corridor</resource_type></resource><resource><id_resource>1278</id_resource><name>Streckengleis-76_2595</name><resource_type>corridor</resource_type></resource><resource><id_resource>949</id_resource><name>Hauptgleis-FRI-A2</name><resource_type>blocking</resource_type></resource><resource><id_resource>1232</id_resource><name>Hauptgleis-FRI-A3</name><resource_type>blocking</resource_type></resource><resource><id_resource>320</id_resource><name>Hauptgleis-LB-3</name><resource_type>blocking</resource_type></resource><resource><id_resource>150</id_resource><name>Hauptgleis-LB-2</name><resource_type>blocking</resource_type></resource><resource><id_resource>1066</id_resource><name>Streckengleis-355_2840</name><resource_type>corridor</resource_type></resource><resource><id_resource>1336</id_resource><name>Hauptgleis-UNT-1</name><resource_type>blocking</resource_type></resource><resource><id_resource>761</id_resource><name>Streckengleis-742_3092</name><resource_type>corridor</resource_type></resource><resource><id_resource>1457</id_resource><name>Hauptgleis-UNT-2</name><resource_type>blocking</resource_type></resource><resource><id_resource>1519</id_resource><name>Hauptgleis-WOES-84</name><resource_type>blocking</resource_type></resource><resource><id_resource>1025</id_resource><name>Hauptgleis-ROL-1</name><resource_type>blocking</resource_type></resource><resource><id_resource>559</id_resource><name>Hauptgleis-ROL-2</name><resource_type>blocking</resource_type></resource><resource><id_resource>599</id_resource><name>Hauptgleis-LB-5</name><resource_type>blocking</resource_type></resource><resource><id_resource>1666</id_resource><name>Hauptgleis-LB-4</name><resource_type>blocking</resource_type></resource><resource><id_resource>1525</id_resource><name>Hauptgleis-AAO-839</name><resource_type>blocking</resource_type></resource><resource><id_resource>1171</id_resource><name>Streckengleis-96_2636</name><resource_type>corridor</resource_type></resource><resource><id_resource>541</id_resource><name>Streckengleis-073_101047229</name><resource_type>corridor</resource_type></resource><resource><id_resource>1586</id_resource><name>Streckengleis-273_3011</name><resource_type>corridor</resource_type></resource><resource><id_resource>1324</id_resource><name>Hauptgleis-BRAG-3</name><resource_type>blocking</resource_type></resource><resource><id_resource>1106</id_resource><name>Hauptgleis-REIK-2</name><resource_type>blocking</resource_type></resource><resource><id_resource>626</id_resource><name>Streckengleis-813_550</name><resource_type>corridor</resource_type></resource><resource><id_resource>754</id_resource><name>Hauptgleis-REIK-1</name><resource_type>blocking</resource_type></resource><resource><id_resource>326</id_resource><name>Streckengleis-114_238</name><resource_type>corridor</resource_type></resource><resource><id_resource>1477</id_resource><name>Streckengleis-317_2703</name><resource_type>corridor</resource_type></resource><resource><id_resource>268</id_resource><name>Streckengleis-491_170</name><resource_type>corridor</resource_type></resource><resource><id_resource>1569</id_resource><name>Streckengleis-295_101088846</name><resource_type>corridor</resource_type></resource><resource><id_resource>241</id_resource><name>Hauptgleis-UZW-4</name><resource_type>blocking</resource_type></resource><resource><id_resource>1668</id_resource><name>Hauptgleis-RBLE-707</name><resource_type>blocking</resource_type></resource><resource><id_resource>829</id_resource><name>Hauptgleis-UZW-3</name><resource_type>blocking</resource_type></resource><resource><id_resource>330</id_resource><name>Streckengleis-55_229</name><resource_type>corridor</resource_type></resource><resource><id_resource>840</id_resource><name>Streckengleis-92_102008544</name><resource_type>corridor</resource_type></resource><resource><id_resource>123</id_resource><name>Streckengleis-641_69</name><resource_type>corridor</resource_type></resource><resource><id_resource>550</id_resource><name>Streckengleis-310_1878</name><resource_type>corridor</resource_type></resource><resource><id_resource>139</id_resource><name>Hauptgleis-WOES-83</name><resource_type>blocking</resource_type></resource><resource><id_resource>608</id_resource><name>Streckengleis-285_2486</name><resource_type>corridor</resource_type></resource><resource><id_resource>767</id_resource><name>Streckengleis-199_2526</name><resource_type>corridor</resource_type></resource><resource><id_resource>221</id_resource><name>Streckengleis-424_864</name><resource_type>corridor</resource_type></resource><resource><id_resource>1551</id_resource><name>Hauptgleis-KLB-509</name><resource_type>blocking</resource_type></resource><resource><id_resource>1086</id_resource><name>Streckengleis-272_101099633</name><resource_type>corridor</resource_type></resource><resource><id_resource>1200</id_resource><name>Hauptgleis-BOSS-804</name><resource_type>blocking</resource_type></resource><resource><id_resource>926</id_resource><name>Streckengleis-965_1424</name><resource_type>corridor</resource_type></resource><resource><id_resource>1231</id_resource><name>Streckengleis-840_1967</name><resource_type>corridor</resource_type></resource><resource><id_resource>928</id_resource><name>Streckengleis-965_1426</name><resource_type>corridor</resource_type></resource><resource><id_resource>38</id_resource><name>Streckengleis-113_53</name><resource_type>corridor</resource_type></resource><resource><id_resource>100</id_resource><name>Hauptgleis-SO-1</name><resource_type>blocking</resource_type></resource><resource><id_resource>446</id_resource><name>Hauptgleis-SO-2</name><resource_type>blocking</resource_type></resource><resource><id_resource>1421</id_resource><name>Streckengleis-113_2021</name><resource_type>corridor</resource_type></resource><resource><id_resource>1575</id_resource><name>Hauptgleis-MDE-3</name><resource_type>blocking</resource_type></resource><resource><id_resource>22</id_resource><name>Hauptgleis-BAV-515</name><resource_type>blocking</resource_type></resource><resource><id_resource>1204</id_resource><name>Hauptgleis-PUI-1</name><resource_type>blocking</resource_type></resource><resource><id_resource>477</id_resource><name>Streckengleis-813_26</name><resource_type>corridor</resource_type></resource><resource><id_resource>308</id_resource><name>Streckengleis-310_2700</name><resource_type>corridor</resource_type></resource><resource><id_resource>977</id_resource><name>Hauptgleis-PUI-2</name><resource_type>blocking</resource_type></resource><resource><id_resource>1619</id_resource><name>Hauptgleis-POZZ-7801</name><resource_type>blocking</resource_type></resource><resource><id_resource>1423</id_resource><name>Streckengleis-118_782</name><resource_type>corridor</resource_type></resource><resource><id_resource>287</id_resource><name>Streckengleis-453_2217</name><resource_type>corridor</resource_type></resource><resource><id_resource>856</id_resource><name>Hauptgleis-WHE-333</name><resource_type>blocking</resource_type></resource><resource><id_resource>1055</id_resource><name>Streckengleis-281_211</name><resource_type>corridor</resource_type></resource><resource><id_resource>1459</id_resource><name>Hauptgleis-MOLS-215</name><resource_type>blocking</resource_type></resource><resource><id_resource>1354</id_resource><name>Streckengleis-242_791</name><resource_type>corridor</resource_type></resource><resource><id_resource>1559</id_resource><name>Streckengleis-130_101096409</name><resource_type>corridor</resource_type></resource><resource><id_resource>966</id_resource><name>Streckengleis-925_1268</name><resource_type>corridor</resource_type></resource><resource><id_resource>1030</id_resource><name>Streckengleis-413_2014</name><resource_type>corridor</resource_type></resource><resource><id_resource>1532</id_resource><name>Streckengleis-850_2680</name><resource_type>corridor</resource_type></resource><resource><id_resource>1642</id_resource><name>Streckengleis-213_2331</name><resource_type>corridor</resource_type></resource><resource><id_resource>8</id_resource><name>Streckengleis-501_101078078</name><resource_type>corridor</resource_type></resource><resource><id_resource>13</id_resource><name>Streckengleis-507_1731</name><resource_type>corridor</resource_type></resource><resource><id_resource>1415</id_resource><name>Streckengleis-158_2139</name><resource_type>corridor</resource_type></resource><resource><id_resource>1053</id_resource><name>Streckengleis-353_206</name><resource_type>corridor</resource_type></resource><resource><id_resource>331</id_resource><name>Hauptgleis-WOES-31</name><resource_type>blocking</resource_type></resource><resource><id_resource>428</id_resource><name>Hauptgleis-WOES-32</name><resource_type>blocking</resource_type></resource><resource><id_resource>612</id_resource><name>Streckengleis-234_185</name><resource_type>corridor</resource_type></resource><resource><id_resource>1213</id_resource><name>Streckengleis-821_1251</name><resource_type>corridor</resource_type></resource><resource><id_resource>167</id_resource><name>Hauptgleis-GLZB-607</name><resource_type>blocking</resource_type></resource><resource><id_resource>1012</id_resource><name>Hauptgleis-COP-3</name><resource_type>blocking</resource_type></resource><resource><id_resource>15</id_resource><name>Streckengleis-510_1196</name><resource_type>corridor</resource_type></resource><resource><id_resource>572</id_resource><name>Hauptgleis-COP-2</name><resource_type>blocking</resource_type></resource><resource><id_resource>1323</id_resource><name>Streckengleis-407_1444</name><resource_type>corridor</resource_type></resource><resource><id_resource>1040</id_resource><name>Hauptgleis-LON-406</name><resource_type>blocking</resource_type></resource><resource><id_resource>650</id_resource><name>Streckengleis-254_667</name><resource_type>corridor</resource_type></resource><resource><id_resource>1385</id_resource><name>Streckengleis-L3_101083547</name><resource_type>corridor</resource_type></resource><resource><id_resource>46</id_resource><name>Streckengleis-603_101092629</name><resource_type>corridor</resource_type></resource><resource><id_resource>361</id_resource><name>Hauptgleis-WAA-3</name><resource_type>blocking</resource_type></resource><resource><id_resource>42</id_resource><name>Streckengleis-117_49</name><resource_type>corridor</resource_type></resource><resource><id_resource>995</id_resource><name>Streckengleis-471_101098728</name><resource_type>corridor</resource_type></resource><resource><id_resource>106</id_resource><name>Hauptgleis-WAA-2</name><resource_type>blocking</resource_type></resource><resource><id_resource>1247</id_resource><name>Streckengleis-862_1678</name><resource_type>corridor</resource_type></resource><resource><id_resource>1249</id_resource><name>Streckengleis-862_1679</name><resource_type>corridor</resource_type></resource><resource><id_resource>281</id_resource><name>Streckengleis-465_381</name><resource_type>corridor</resource_type></resource><resource><id_resource>255</id_resource><name>dummy</name><resource_type>blocking</resource_type></resource><resource><id_resource>1614</id_resource><name>Streckengleis-235_341</name><resource_type>corridor</resource_type></resource><resource><id_resource>895</id_resource><name>Streckengleis-506_1982</name><resource_type>corridor</resource_type></resource><resource><id_resource>337</id_resource><name>Hauptgleis-DK-3</name><resource_type>blocking</resource_type></resource><resource><id_resource>133</id_resource><name>Hauptgleis-DK-4</name><resource_type>blocking</resource_type></resource><resource><id_resource>1202</id_resource><name>Hauptgleis-GRV-2</name><resource_type>blocking</resource_type></resource><resource><id_resource>979</id_resource><name>Hauptgleis-GRV-3</name><resource_type>blocking</resource_type></resource><resource><id_resource>844</id_resource><name>Hauptgleis-ESL-2</name><resource_type>blocking</resource_type></resource><resource><id_resource>1443</id_resource><name>Hauptgleis-SCBU-2</name><resource_type>blocking</resource_type></resource><resource><id_resource>1351</id_resource><name>Hauptgleis-SCBU-1</name><resource_type>blocking</resource_type></resource><resource><id_resource>285</id_resource><name>Streckengleis-457_150</name><resource_type>corridor</resource_type></resource><resource><id_resource>283</id_resource><name>Streckengleis-3_151</name><resource_type>corridor</resource_type></resource><resource><id_resource>861</id_resource><name>Streckengleis-337_101096408</name><resource_type>corridor</resource_type></resource><resource><id_resource>1329</id_resource><name>Streckengleis-104_808</name><resource_type>corridor</resource_type></resource><resource><id_resource>1026</id_resource><name>Streckengleis-417_1290</name><resource_type>corridor</resource_type></resource><resource><id_resource>107</id_resource><name>Streckengleis-661_78</name><resource_type>corridor</resource_type></resource><resource><id_resource>1490</id_resource><name>Streckengleis-2_374</name><resource_type>corridor</resource_type></resource><resource><id_resource>262</id_resource><name>Streckengleis-504_1831</name><resource_type>corridor</resource_type></resource><resource><id_resource>201</id_resource><name>Streckengleis-118_1076</name><resource_type>corridor</resource_type></resource><resource><id_resource>1237</id_resource><name>Streckengleis-851_2925</name><resource_type>corridor</resource_type></resource><resource><id_resource>145</id_resource><name>Hauptgleis-AAO-439</name><resource_type>blocking</resource_type></resource><resource><id_resource>1083</id_resource><name>Streckengleis-140_1653</name><resource_type>corridor</resource_type></resource><resource><id_resource>398</id_resource><name>Streckengleis-196_556</name><resource_type>corridor</resource_type></resource><resource><id_resource>647</id_resource><name>Hauptgleis-WF-3</name><resource_type>blocking</resource_type></resource><resource><id_resource>1403</id_resource><name>Hauptgleis-MAH-2</name><resource_type>blocking</resource_type></resource><resource><id_resource>1018</id_resource><name>Hauptgleis-NY-2</name><resource_type>blocking</resource_type></resource><resource><id_resource>739</id_resource><name>Streckengleis-141_2793</name><resource_type>corridor</resource_type></resource><resource><id_resource>566</id_resource><name>Hauptgleis-NY-1</name><resource_type>blocking</resource_type></resource><resource><id_resource>490</id_resource><name>Streckengleis-232_38</name><resource_type>corridor</resource_type></resource><resource><id_resource>971</id_resource><name>Hauptgleis-OR-917</name><resource_type>blocking</resource_type></resource><resource><id_resource>1264</id_resource><name>Hauptgleis-BOS-278</name><resource_type>blocking</resource_type></resource><resource><id_resource>1259</id_resource><name>Streckengleis-1_2847</name><resource_type>corridor</resource_type></resource><resource><id_resource>1170</id_resource><name>Hauptgleis-WF-1</name><resource_type>blocking</resource_type></resource><resource><id_resource>1139</id_resource><name>Hauptgleis-BNWD-204</name><resource_type>blocking</resource_type></resource><resource><id_resource>675</id_resource><name>Streckengleis-222_1078</name><resource_type>corridor</resource_type></resource><resource><id_resource>393</id_resource><name>Hauptgleis-MUEH-189</name><resource_type>blocking</resource_type></resource><resource><id_resource>1367</id_resource><name>Streckengleis-226_786</name><resource_type>corridor</resource_type></resource><resource><id_resource>653</id_resource><name>Hauptgleis-HM-250</name><resource_type>blocking</resource_type></resource><resource><id_resource>910</id_resource><name>Streckengleis-171_2630</name><resource_type>corridor</resource_type></resource><resource><id_resource>278</id_resource><name>Hauptgleis-RTW-2</name><resource_type>blocking</resource_type></resource><resource><id_resource>226</id_resource><name>Hauptgleis-ESL-1</name><resource_type>blocking</resource_type></resource><resource><id_resource>1494</id_resource><name>Hauptgleis-RTW-1</name><resource_type>blocking</resource_type></resource><resource><id_resource>1306</id_resource><name>Streckengleis-L4_101083546</name><resource_type>corridor</resource_type></resource><resource><id_resource>1625</id_resource><name>Hauptgleis-RYUE-7241</name><resource_type>blocking</resource_type></resource><resource><id_resource>756</id_resource><name>Streckengleis-710_3095</name><resource_type>corridor</resource_type></resource><resource><id_resource>1589</id_resource><name>Streckengleis-269_303</name><resource_type>corridor</resource_type></resource><resource><id_resource>538</id_resource><name>Streckengleis-003_101047248</name><resource_type>corridor</resource_type></resource><resource><id_resource>52</id_resource><name>Streckengleis-130_39</name><resource_type>corridor</resource_type></resource><resource><id_resource>323</id_resource><name>Streckengleis-337_4130</name><resource_type>corridor</resource_type></resource><resource><id_resource>1518</id_resource><name>Hauptgleis-RTW-3</name><resource_type>blocking</resource_type></resource><resource><id_resource>997</id_resource><name>Hauptgleis-GE-A4</name><resource_type>blocking</resource_type></resource><resource><id_resource>587</id_resource><name>Hauptgleis-GE-A2</name><resource_type>blocking</resource_type></resource><resource><id_resource>524</id_resource><name>Streckengleis-32_101039465</name><resource_type>corridor</resource_type></resource><resource><id_resource>1479</id_resource><name>Hauptgleis-CH-8</name><resource_type>blocking</resource_type></resource><resource><id_resource>774</id_resource><name>Hauptgleis-PFZ-2</name><resource_type>blocking</resource_type></resource><resource><id_resource>72</id_resource><name>Hauptgleis-TUE-1</name><resource_type>blocking</resource_type></resource><resource><id_resource>1315</id_resource><name>Hauptgleis-CH-9</name><resource_type>blocking</resource_type></resource><resource><id_resource>474</id_resource><name>Hauptgleis-TUE-2</name><resource_type>blocking</resource_type></resource><resource><id_resource>1436</id_resource><name>Streckengleis-135_1717</name><resource_type>corridor</resource_type></resource><resource><id_resource>693</id_resource><name>Streckengleis-663_101085411</name><resource_type>corridor</resource_type></resource><resource><id_resource>594</id_resource><name>Streckengleis-965_2332</name><resource_type>corridor</resource_type></resource><resource><id_resource>1031</id_resource><name>Hauptgleis-ETOY-412</name><resource_type>blocking</resource_type></resource><resource><id_resource>881</id_resource><name>Hauptgleis-ZUE-A17</name><resource_type>blocking</resource_type></resource><resource><id_resource>404</id_resource><name>Hauptgleis-ZUE-A16</name><resource_type>blocking</resource_type></resource><resource><id_resource>640</id_resource><name>Streckengleis-267_2079</name><resource_type>corridor</resource_type></resource><resource><id_resource>1664</id_resource><name>Hauptgleis-ZUE-A18</name><resource_type>blocking</resource_type></resource><resource><id_resource>368</id_resource><name>Streckengleis-101_3016</name><resource_type>corridor</resource_type></resource><resource><id_resource>175</id_resource><name>Hauptgleis-ZVB-R64</name><resource_type>blocking</resource_type></resource><resource><id_resource>903</id_resource><name>Streckengleis-900_2165</name><resource_type>corridor</resource_type></resource><resource><id_resource>271</id_resource><name>Streckengleis-486_166</name><resource_type>corridor</resource_type></resource><resource><id_resource>603</id_resource><name>Hauptgleis-RBLE-713</name><resource_type>blocking</resource_type></resource><resource><id_resource>27</id_resource><name>Streckengleis-118_1497</name><resource_type>corridor</resource_type></resource><resource><id_resource>1663</id_resource><name>Hauptgleis-RBLE-711</name><resource_type>blocking</resource_type></resource><resource><id_resource>1481</id_resource><name>Hauptgleis-RTRH-641</name><resource_type>blocking</resource_type></resource><resource><id_resource>291</id_resource><name>Hauptgleis-RTRH-644</name><resource_type>blocking</resource_type></resource><resource><id_resource>1229</id_resource><name>Streckengleis-838_1965</name><resource_type>corridor</resource_type></resource><resource><id_resource>462</id_resource><name>Hauptgleis-LEN-2</name><resource_type>blocking</resource_type></resource><resource><id_resource>1508</id_resource><name>Streckengleis-143_2796</name><resource_type>corridor</resource_type></resource><resource><id_resource>84</id_resource><name>Hauptgleis-LEN-1</name><resource_type>blocking</resource_type></resource><resource><id_resource>1529</id_resource><name>Hauptgleis-MAEG-5</name><resource_type>blocking</resource_type></resource><resource><id_resource>155</id_resource><name>Hauptgleis-MAEG-4</name><resource_type>blocking</resource_type></resource><resource><id_resource>827</id_resource><name>Hauptgleis-FLA-1</name><resource_type>blocking</resource_type></resource><resource><id_resource>1536</id_resource><name>Streckengleis-308_2701</name><resource_type>corridor</resource_type></resource><resource><id_resource>243</id_resource><name>Hauptgleis-FLA-2</name><resource_type>blocking</resource_type></resource><resource><id_resource>964</id_resource><name>Streckengleis-926_1960</name><resource_type>corridor</resource_type></resource><resource><id_resource>1583</id_resource><name>Hauptgleis-LAM-275</name><resource_type>blocking</resource_type></resource><resource><id_resource>244</id_resource><name>Streckengleis-292_101100419</name><resource_type>corridor</resource_type></resource><resource><id_resource>1492</id_resource><name>Hauptgleis-HB-1</name><resource_type>blocking</resource_type></resource><resource><id_resource>219</id_resource><name>Streckengleis-429_1573</name><resource_type>corridor</resource_type></resource><resource><id_resource>280</id_resource><name>Hauptgleis-HB-2</name><resource_type>blocking</resource_type></resource><resource><id_resource>804</id_resource><name>Streckengleis-404_714</name><resource_type>corridor</resource_type></resource><resource><id_resource>315</id_resource><name>Hauptgleis-MAEG-3</name><resource_type>blocking</resource_type></resource><resource><id_resource>1499</id_resource><name>Streckengleis-385_163</name><resource_type>corridor</resource_type></resource><resource><id_resource>718</id_resource><name>Streckengleis-003_102002184</name><resource_type>corridor</resource_type></resource><resource><id_resource>1401</id_resource><name>Hauptgleis-BI-4</name><resource_type>blocking</resource_type></resource><resource><id_resource>998</id_resource><name>Streckengleis-442_1672</name><resource_type>corridor</resource_type></resource><resource><id_resource>74</id_resource><name>Hauptgleis-BI-3</name><resource_type>blocking</resource_type></resource><resource><id_resource>472</id_resource><name>Hauptgleis-BI-5</name><resource_type>blocking</resource_type></resource><resource><id_resource>19</id_resource><name>Streckengleis-31_101039464</name><resource_type>corridor</resource_type></resource><resource><id_resource>813</id_resource><name>Hauptgleis-SILB-449</name><resource_type>blocking</resource_type></resource><resource><id_resource>1482</id_resource><name>Streckengleis-671_145</name><resource_type>corridor</resource_type></resource><resource><id_resource>1554</id_resource><name>Streckengleis-510_1101</name><resource_type>corridor</resource_type></resource><resource><id_resource>389</id_resource><name>Hauptgleis-MI-4</name><resource_type>blocking</resource_type></resource><resource><id_resource>88</id_resource><name>Hauptgleis-BET-682</name><resource_type>blocking</resource_type></resource><resource><id_resource>1662</id_resource><name>Hauptgleis-MI-2</name><resource_type>blocking</resource_type></resource><resource><id_resource>1402</id_resource><name>Streckengleis-901_132</name><resource_type>corridor</resource_type></resource><resource><id_resource>1262</id_resource><name>Hauptgleis-MI-3</name><resource_type>blocking</resource_type></resource><resource><id_resource>350</id_resource><name>Streckengleis-546_67</name><resource_type>corridor</resource_type></resource><resource><id_resource>1505</id_resource>