<?xml version="1.0" encoding="UTF-8" standalone="yes"?><!DOCTYPE root [
<!ELEMENT root (resource+, path*, time_point*, time_profile*, routed_job*, job*, job_op*, setup_removal_table*, machine*, platform*, connection*)>
<!ELEMENT resource (id_resource, name, resource_type, info1*, info2*)>
<!ELEMENT id_resource (#PCDATA)>
<!ELEMENT resource_type (#PCDATA)>
<!ELEMENT info1 (#PCDATA)>
<!ELEMENT info2 (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT path (id_path, resource_list_elem+)>
<!ELEMENT resource_list_elem (id_resource)>
<!ELEMENT id_path (#PCDATA)>
<!ELEMENT time_point (id_time_point, processing_time*, perishability_time*,release_no_timeshift*, release_time*, due_date_no_timeshift*, due_date_time*, deadline_no_timeshift*, deadline_time*, weight_obj*, setup_time*, removal_time*, dependent_setup_type*, dependent_removal_type*, route_booking_forward*, route_booking_backward*)>
<!ELEMENT id_time_point (#PCDATA)>
<!ELEMENT processing_time (#PCDATA)>
<!ELEMENT perishability_time (#PCDATA)>
<!ELEMENT release_no_timeshift (#PCDATA)>
<!ELEMENT release_time (#PCDATA)>
<!ELEMENT due_date_no_timeshift (#PCDATA)>
<!ELEMENT due_date_time (#PCDATA)>
<!ELEMENT deadline_no_timeshift (#PCDATA)>
<!ELEMENT deadline_time (#PCDATA)>
<!ELEMENT weight_obj (#PCDATA)>
<!ELEMENT setup_time (#PCDATA)>
<!ELEMENT removal_time (#PCDATA)>
<!ELEMENT dependent_setup_type (#PCDATA)>
<!ELEMENT dependent_removal_type (#PCDATA)>
<!ELEMENT route_booking_forward (#PCDATA)>
<!ELEMENT route_booking_backward (#PCDATA)>
<!ELEMENT time_profile (id_time_profile, id_path, time_point_list_elem+)>
<!ELEMENT time_point_list_elem (id_time_point)>
<!ELEMENT id_time_profile (#PCDATA)>
<!ELEMENT routed_job (id_routed_job, job_type, time_shift, id_time_profile, weight_obj*)>
<!ELEMENT routed_job_list_elem (id_routed_job)>
<!ELEMENT job (id_job, name, routed_job_list_elem+, multiple_routings_list_elem+)>
<!ELEMENT multiple_routings_list_elem (id_resource, time_profile_list_elem+)>
<!ELEMENT time_profile_list_elem (id_time_profile)>
<!ELEMENT id_job (#PCDATA)>
<!ELEMENT id_routed_job (#PCDATA)>
<!ELEMENT job_type (#PCDATA)>
<!ELEMENT time_shift (#PCDATA)>
<!ELEMENT job_op (id_job, operation+)>
<!ELEMENT operation (id_resource, time_point)>
<!ELEMENT setup_removal_table (table_entry+)>
<!ELEMENT table_entry (dependent_type1, dependent_type2,  setup_removal_type, dependent_time)>
<!ELEMENT dependent_type1 (#PCDATA)>
<!ELEMENT dependent_type2 (#PCDATA)>
<!ELEMENT setup_removal_type (#PCDATA)>
<!ELEMENT dependent_time (#PCDATA)>
<!ELEMENT machine (resource_list_elem+)>
<!ELEMENT platform (resource_list_elem+)>
<!ELEMENT connection (id_job_from, id_resource_from, id_job_to, id_resource_to, connection_weight, connection_price, is_passenger)>
<!ELEMENT id_job_from (#PCDATA)>
<!ELEMENT id_resource_from (#PCDATA)>
<!ELEMENT id_job_to (#PCDATA)>
<!ELEMENT id_resource_to (#PCDATA)>
<!ELEMENT connection_weight (#PCDATA)>
<!ELEMENT connection_price (#PCDATA)>
<!ELEMENT is_passenger (#PCDATA)>]><root><resource><id_resource>34</id_resource><name>UNT_MG</name><resource_type>corridor</resource_type></resource><resource><id_resource>17</id_resource><name>BIL_RG</name><resource_type>corridor</resource_type></resource><resource><id_resource>35</id_resource><name>MG122</name><resource_type>blocking</resource_type></resource><resource><id_resource>13</id_resource><name>BIL_ZB</name><resource_type>corridor</resource_type></resource><resource><id_resource>30</id_resource><name>WAL_MOLS</name><resource_type>corridor</resource_type></resource><resource><id_resource>42</id_resource><name>ZB6</name><resource_type>blocking</resource_type></resource><resource><id_resource>55</id_resource><name>UNT2</name><resource_type>blocking</resource_type></resource><resource><id_resource>47</id_resource><name>ZB9</name><resource_type>blocking</resource_type></resource><resource><id_resource>14</id_resource><name>dummy</name><resource_type>blocking</resource_type></resource><resource><id_resource>33</id_resource><name>UNT1</name><resource_type>blocking</resource_type></resource><resource><id_resource>56</id_resource><name>UNT_MOLS</name><resource_type>corridor</resource_type></resource><resource><id_resource>36</id_resource><name>MG_TIEF</name><resource_type>corridor</resource_type></resource><resource><id_resource>5</id_resource><name>LA_SIB</name><resource_type>corridor</resource_type></resource><resource><id_resource>37</id_resource><name>1Spur_MH_TIEF</name><resource_type>corridor</resource_type></resource><resource><id_resource>9</id_resource><name>SCBU_RG</name><resource_type>corridor</resource_type></resource><resource><id_resource>59</id_resource><name>WAL3</name><resource_type>blocking</resource_type></resource><resource><id_resource>58</id_resource><name>MOLS_WAL</name><resource_type>corridor</resource_type></resource><resource><id_resource>29</id_resource><name>WAL4</name><resource_type>blocking</resource_type></resource><resource><id_resource>24</id_resource><name>SA_MELS</name><resource_type>corridor</resource_type></resource><resource><id_resource>10</id_resource><name>RG4</name><resource_type>blocking</resource_type></resource><resource><id_resource>18</id_resource><name>RG3</name><resource_type>blocking</resource_type></resource><resource><id_resource>22</id_resource><name>SIB3</name><resource_type>blocking</resource_type></resource><resource><id_resource>51</id_resource><name>MH228</name><resource_type>blocking</resource_type></resource><resource><id_resource>39</id_resource><name>MH_WN</name><resource_type>corridor</resource_type></resource><resource><id_resource>19</id_resource><name>RG_SCBU</name><resource_type>corridor</resource_type></resource><resource><id_resource>31</id_resource><name>MOLS115</name><resource_type>blocking</resource_type></resource><resource><id_resource>52</id_resource><name>TIEF_MG</name><resource_type>corridor</resource_type></resource><resource><id_resource>25</id_resource><name>MELS108</name><resource_type>blocking</resource_type></resource><resource><id_resource>15</id_resource><name>ZB_BIL</name><resource_type>corridor</resource_type></resource><resource><id_resource>8</id_resource><name>SCBU145</name><resource_type>blocking</resource_type></resource><resource><id_resource>21</id_resource><name>SCBU_SIB</name><resource_type>corridor</resource_type></resource><resource><id_resource>23</id_resource><name>SIB_LA</name><resource_type>corridor</resource_type></resource><resource><id_resource>6</id_resource><name>SIB4</name><resource_type>blocking</resource_type></resource><resource><id_resource>64</id_resource><name>MELS_SA</name><resource_type>corridor</resource_type></resource><resource><id_resource>1</id_resource><name>PF_ALTD</name><resource_type>corridor</resource_type></resource><resource><id_resource>40</id_resource><name>WN4</name><resource_type>blocking</resource_type></resource><resource><id_resource>3</id_resource><name>ALTD_LA</name><resource_type>corridor</resource_type></resource><resource><id_resource>49</id_resource><name>WN3</name><resource_type>blocking</resource_type></resource><resource><id_resource>46</id_resource><name>ALTD_PF</name><resource_type>corridor</resource_type></resource><resource><id_resource>45</id_resource><name>ALTD237</name><resource_type>blocking</resource_type></resource><resource><id_resource>62</id_resource><name>FMS_MELS</name><resource_type>corridor</resource_type></resource><resource><id_resource>53</id_resource><name>MG222</name><resource_type>blocking</resource_type></resource><resource><id_resource>54</id_resource><name>MG_UNT</name><resource_type>corridor</resource_type></resource><resource><id_resource>11</id_resource><name>RG_BIL</name><resource_type>corridor</resource_type></resource><resource><id_resource>4</id_resource><name>LA2</name><resource_type>blocking</resource_type></resource><resource><id_resource>48</id_resource><name>ZB_WN</name><resource_type>corridor</resource_type></resource><resource><id_resource>43</id_resource><name>LA3</name><resource_type>blocking</resource_type></resource><resource><id_resource>65</id_resource><name>ZB99</name><resource_type>blocking</resource_type></resource><resource><id_resource>38</id_resource><name>MH128</name><resource_type>blocking</resource_type></resource><resource><id_resource>27</id_resource><name>FMS3</name><resource_type>blocking</resource_type></resource><resource><id_resource>63</id_resource><name>MELS208</name><resource_type>blocking</resource_type></resource><resource><id_resource>61</id_resource><name>FMS4</name><resource_type>blocking</resource_type></resource><resource><id_resource>57</id_resource><name>MOLS215</name><resource_type>blocking</resource_type></resource><resource><id_resource>60</id_resource><name>WAL_FMS</name><resource_type>corridor</resource_type></resource><resource><id_resource>50</id_resource><name>WN_MH</name><resource_type>corridor</resource_type></resource><resource><id_resource>32</id_resource><name>MOLS_UNT</name><resource_type>corridor</resource_type></resource><resource><id_resource>12</id_resource><name>BIL4</name><resource_type>blocking</resource_type></resource><resource><id_resource>16</id_resource><name>BIL3</name><resource_type>blocking</resource_type></resource><resource><id_resource>20</id_resource><name>SCBU245</name><resource_type>blocking</resource_type></resource><resource><id_resource>28</id_resource><name>FMS_WAL</name><resource_type>corridor</resource_type></resource><resource><id_resource>26</id_resource><name>MELS_FMS</name><resource_type>corridor</resource_type></resource><resource><id_resource>44</id_resource><name>LA_ALTD</name><resource_type>corridor</resource_type></resource><resource><id_resource>41</id_resource><name>WN_ZB</name><resource_type>corridor</resource_type></resource><resource><id_resource>2</id_resource><name>ALTD137</name><resource_type>blocking</resource_type></resource><resource><id_resource>7</id_resource><name>SIB_SCBU</name><resource_type>corridor</resource_type></resource><path><id_path>81</id_path><resource_list_elem><id_resource>15</id_resource></resource_list_elem><resource_list_elem><id_resource>16</id_resource></resource_list_elem><resource_list_elem><id_resource>17</id_resource></resource_list_elem><resource_list_elem><id_resource>18</id_resource></resource_list_elem><resource_list_elem><id_resource>19</id_resource></resource_list_elem><resource_list_elem><id_resource>20</id_resource></resource_list_elem><resource_list_elem><id_resource>21</id_resource></resource_list_elem><resource_list_elem><id_resource>22</id_resource></resource_list_elem><resource_list_elem><id_resource>23</id_resource></resource_list_elem><resource_list_elem><id_resource>14</id_resource></resource_list_elem></path><path><id_path>66</id_path><resource_list_elem><id_resource>1</id_resource></resource_list_elem><resource_list_elem><id_resource>2</id_resource></resource_list_elem><resource_list_elem><id_resource>3</id_resource></resource_list_elem><resource_list_elem><id_resource>4</id_resource></resource_list_elem><resource_list_elem><id_resource>5</id_resource></resource_list_elem><resource_list_elem><id_resource>6</id_resource></resource_list_elem><resource_list_elem><id_resource>7</id_resource></resource_list_elem><resource_list_elem><id_resource>8</id_resource></resource_list_elem><resource_list_elem><id_resource>9</id_resource></resource_list_elem><resource_list_elem><id_resource>10</id_resource></resource_list_elem><resource_list_elem><id_resource>11</id_resource></resource_list_elem><resource_list_elem><id_resource>12</id_resource></resource_list_elem><resource_list_elem><id_resource>13</id_resource></resource_list_elem><resource_list_elem><id_resource>14</id_resource></resource_list_elem></path><path><id_path>92</id_path><resource_list_elem><id_resource>24</id_resource></resource_list_elem><resource_list_elem><id_resource>25</id_resource></resource_list_elem><resource_list_elem><id_resource>26</id_resource></resource_list_elem><resource_list_elem><id_resource>27</id_resource></resource_list_elem><resource_list_elem><id_resource>28</id_resource></resource_list_elem><resource_list_elem><id_resource>29</id_resource></resource_list_elem><resource_list_elem><id_resource>30</id_resource></resource_list_elem><resource_list_elem><id_resource>31</id_resource></resource_list_elem><resource_list_elem><id_resource>32</id_resource></resource_list_elem><resource_list_elem><id_resource>33</id_resource></resource_list_elem><resource_list_elem><id_resource>34</id_resource></resource_list_elem><resource_list_elem><id_resource>35</id_resource></resource_list_elem><resource_list_elem><id_resource>36</id_resource></resource_list_elem><resource_list_elem><id_resource>37</id_resource></resource_list_elem><resource_list_elem><id_resource>38</id_resource></resource_list_elem><resource_list_elem><id_resource>39</id_resource></resource_list_elem><resource_list_elem><id_resource>40</id_resource></resource_list_elem><resource_list_elem><id_resource>41</id_resource></resource_list_elem><resource_list_elem><id_resource>42</id_resource></resource_list_elem><resource_list_elem><id_resource>15</id_resource></resource_list_elem><resource_list_elem><id_resource>16</id_resource></resource_list_elem><resource_list_elem><id_resource>17</id_resource></resource_list_elem><resource_list_elem><id_resource>18</id_resource></resource_list_elem><resource_list_elem><id_resource>19</id_resource></resource_list_elem><resource_list_elem><id_resource>20</id_resource></resource_list_elem><resource_list_elem><id_resource>21</id_resource></resource_list_elem><resource_list_elem><id_resource>22</id_resource></resource_list_elem><resource_list_elem><id_resource>23</id_resource></resource_list_elem><resource_list_elem><id_resource>43</id_resource></resource_list_elem><resource_list_elem><id_resource>44</id_resource></resource_list_elem><resource_list_elem><id_resource>45</id_resource></resource_list_elem><resource_list_elem><id_resource>46</id_resource></resource_list_elem><resource_list_elem><id_resource>14</id_resource></resource_list_elem></path><path><id_path>126</id_path><resource_list_elem><id_resource>24</id_resource></resource_list_elem><resource_list_elem><id_resource>25</id_resource></resource_list_elem><resource_list_elem><id_resource>26</id_resource></resource_list_elem><resource_list_elem><id_resource>27</id_resource></resource_list_elem><resource_list_elem><id_resource>28</id_resource></resource_list_elem><resource_list_elem><id_resource>29</id_resource></resource_list_elem><resource_list_elem><id_resource>30</id_resource></resource_list_elem><resource_list_elem><id_resource>31</id_resource></resource_list_elem><resource_list_elem><id_resource>32</id_resource></resource_list_elem><resource_list_elem><id_resource>33</id_resource></resource_list_elem><resource_list_elem><id_resource>34</id_resource></resource_list_elem><resource_list_elem><id_resource>35</id_resource></resource_list_elem><resource_list_elem><id_resource>36</id_resource></resource_list_elem><resource_list_elem><id_resource>37</id_resource></resource_list_elem><resource_list_elem><id_resource>38</id_resource></resource_list_elem><resource_list_elem><id_resource>39</id_resource></resource_list_elem><resource_list_elem><id_resource>40</id_resource></resource_list_elem><resource_list_elem><id_resource>41</id_resource></resource_list_elem><resource_list_elem><id_resource>42</id_resource></resource_list_elem><resource_list_elem><id_resource>15</id_resource></resource_list_elem><resource_list_elem><id_resource>16</id_resource></resource_list_elem><resource_list_elem><id_resource>17</id_resource></resource_list_elem><resource_list_elem><id_resource>18</id_resource></resource_list_elem><resource_list_elem><id_resource>19</id_resource></resource_list_elem><resource_list_elem><id_resource>20</id_resource></resource_list_elem><resource_list_elem><id_resource>21</id_resource></resource_list_elem><resource_list_elem><id_resource>22</id_resource></resource_list_elem><resource_list_elem><id_resource>23</id_resource></resource_list_elem><resource_list_elem><id_resource>43</id_resource></resource_list_elem><resource_list_elem><id_resource>44</id_resource></resource_list_elem><resource_list_elem><id_resource>45</id_resource></resource_list_elem><resource_list_elem><id_resource>46</id_resource></resource_list_elem><resource_list_elem><id_resource>14</id_resource></resource_list_elem></path><path><id_path>194</id_path><resource_list_elem><id_resource>1</id_resource></resource_list_elem><resource_list_elem><id_resource>2</id_resource></resource_list_elem><resource_list_elem><id_resource>3</id_resource></resource_list_elem><resource_list_elem><id_resource>4</id_resource></resource_list_elem><resource_list_elem><id_resource>5</id_resource></resource_list_elem><resource_list_elem><id_resource>6</id_resource></resource_list_elem><resource_list_elem><id_resource>7</id_resource></resource_list_elem><resource_list_elem><id_resource>8</id_resource></resource_list_elem><resource_list_elem><id_resource>9</id_resource></resource_list_elem><resource_list_elem><id_resource>10</id_resource></resource_list_elem><resource_list_elem><id_resource>11</id_resource></resource_list_elem><resource_list_elem><id_resource>12</id_resource></resource_list_elem><resource_list_elem><id_resource>13</id_resource></resource_list_elem><resource_list_elem><id_resource>47</id_resource></resource_list_elem><resource_list_elem><id_resource>48</id_resource></resource_list_elem><resource_list_elem><id_resource>49</id_resource></resource_list_elem><resource_list_elem><id_resource>50</id_resource></resource_list_elem><resource_list_elem><id_resource>51</id_resource></resource_list_elem><resource_list_elem><id_resource>37</id_resource></resource_list_elem><resource_list_elem><id_resource>52</id_resource></resource_list_elem><resource_list_elem><id_resource>53</id_resource></resource_list_elem><resource_list_elem><id_resource>54</id_resource></resource_list_elem><resource_list_elem><id_resource>55</id_resource></resource_list_elem><resource_list_elem><id_resource>56</id_resource></resource_list_elem><resource_list_elem><id_resource>57</id_resource></resource_list_elem><resource_list_elem><id_resource>58</id_resource></resource_list_elem><resource_list_elem><id_resource>59</id_resource></resource_list_elem><resource_list_elem><id_resource>60</id_resource></resource_list_elem><resource_list_elem><id_resource>61</id_resource></resource_list_elem><resource_list_elem><id_resource>62</id_resource></resource_list_elem><resource_list_elem><id_resource>63</id_resource></resource_list_elem><resource_list_elem><id_resource>64</id_resource></resource_list_elem><resource_list_elem><id_resource>14</id_resource></resource_list_elem></path><path><id_path>160</id_path><resource_list_elem><id_resource>1</id_resource></resource_list_elem><resource_list_elem><id_resource>2</id_resource></resource_list_elem><resource_list_elem><id_resource>3</id_resource></resource_list_elem><resource_list_elem><id_resource>4</id_resource></resource_list_elem><resource_list_elem><id_resource>5</id_resource></resource_list_elem><resource_list_elem><id_resource>6</id_resource></resource_list_elem><resource_list_elem><id_resource>7</id_resource></resource_list_elem><resource_list_elem><id_resource>8</id_resource></resource_list_elem><resource_list_elem><id_resource>9</id_resource></resource_list_elem><resource_list_elem><id_resource>10</id_resource></resource_list_elem><resource_list_elem><id_resource>11</id_resource></resource_list_elem><resource_list_elem><id_resource>12</id_resource></resource_list_elem><resource_list_elem><id_resource>13</id_resource></resource_list_elem><resource_list_elem><id_resource>47</id_resource></resource_list_elem><resource_list_elem><id_resource>48</id_resource></resource_list_elem><resource_list_elem><id_resource>49</id_resource></resource_list_elem><resource_list_elem><id_resource>50</id_resource></resource_list_elem><resource_list_elem><id_resource>51</id_resource></resource_list_elem><resource_list_elem><id_resource>37</id_resource></resource_list_elem><resource_list_elem><id_resource>52</id_resource></resource_list_elem><resource_list_elem><id_resource>53</id_resource></resource_list_elem><resource_list_elem><id_resource>54</id_resource></resource_list_elem><resource_list_elem><id_resource>55</id_resource></resource_list_elem><resource_list_elem><id_resource>56</id_resource></resource_list_elem><resource_list_elem><id_resource>57</id_resource></resource_list_elem><resource_list_elem><id_resource>58</id_resource></resource_list_elem><resource_list_elem><id_resource>59</id_resource></resource_list_elem><resource_list_elem><id_resource>60</id_resource></resource_list_elem><resource_list_elem><id_resource>61</id_resource></resource_list_elem><resource_list_elem><id_resource>62</id_resource></resource_list_elem><resource_list_elem><id_resource>63</id_resource></resource_list_elem><resource_list_elem><id_resource>64</id_resource></resource_list_elem><resource_list_elem><id_resource>14</id_resource></resource_list_elem></path><path><id_path>228</id_path><resource_list_elem><id_resource>24</id_resource></resource_list_elem><resource_list_elem><id_resource>25</id_resource></resource_list_elem><resource_list_elem><id_resource>26</id_resource></resource_list_elem><resource_list_elem><id_resource>27</id_resource></resource_list_elem><resource_list_elem><id_resource>28</id_resource></resource_list_elem><resource_list_elem><id_resource>29</id_resource></resource_list_elem><resource_list_elem><id_resource>30</id_resource></resource_list_elem><resource_list_elem><id_resource>31</id_resource></resource_list_elem><resource_list_elem><id_resource>32</id_resource></resource_list_elem><resource_list_elem><id_resource>33</id_resource></resource_list_elem><resource_list_elem><id_resource>34</id_resource></resource_list_elem><resource_list_elem><id_resource>35</id_resource></resource_list_elem><resource_list_elem><id_resource>36</id_resource></resource_list_elem><resource_list_elem><id_resource>37</id_resource></resource_list_elem><resource_list_elem><id_resource>38</id_resource></resource_list_elem><resource_list_elem><id_resource>39</id_resource></resource_list_elem><resource_list_elem><id_resource>40</id_resource></resource_list_elem><resource_list_elem><id_resource>41</id_resource></resource_list_elem><resource_list_elem><id_resource>42</id_resource></resource_list_elem><resource_list_elem><id_resource>15</id_resource></resource_list_elem><resource_list_elem><id_resource>16</id_resource></resource_list_elem><resource_list_elem><id_resource>17</id_resource></resource_list_elem><resource_list_elem><id_resource>18</id_resource></resource_list_elem><resource_list_elem><id_resource>19</id_resource></resource_list_elem><resource_list_elem><id_resource>20</id_resource></resource_list_elem><resource_list_elem><id_resource>21</id_resource></resource_list_elem><resource_list_elem><id_resource>22</id_resource></resource_list_elem><resource_list_elem><id_resource>23</id_resource></resource_list_elem><resource_list_elem><id_resource>43</id_resource></resource_list_elem><resource_list_elem><id_resource>44</id_resource></resource_list_elem><resource_list_elem><id_resource>45</id_resource></resource_list_elem><resource_list_elem><id_resource>46</id_resource></resource_list_elem><resource_list_elem><id_resource>14</id_resource></resource_list_elem></path><path><id_path>262</id_path><resource_list_elem><id_resource>1</id_resource></resource_list_elem><resource_list_elem><id_resource>2</id_resource></resource_list_elem><resource_list_elem><id_resource>3</id_resource></resource_list_elem><resource_list_elem><id_resource>4</id_resource></resource_list_elem><resource_list_elem><id_resource>5</id_resource></resource_list_elem><resource_list_elem><id_resource>6</id_resource></resource_list_elem><resource_list_elem><id_resource>7</id_resource></resource_list_elem><resource_list_elem><id_resource>8</id_resource></resource_list_elem><resource_list_elem><id_resource>9</id_resource></resource_list_elem><resource_list_elem><id_resource>10</id_resource></resource_list_elem><resource_list_elem><id_resource>11</id_resource></resource_list_elem><resource_list_elem><id_resource>12</id_resource></resource_list_elem><resource_list_elem><id_resource>13</id_resource></resource_list_elem><resource_list_elem><id_resource>47</id_resource></resource_list_elem><resource_list_elem><id_resource>48</id_resource></resource_list_elem><resource_list_elem><id_resource>49</id_resource></resource_list_elem><resource_list_elem><id_resource>50</id_resource></resource_list_elem><resource_list_elem><id_resource>51</id_resource></resource_list_elem><resource_list_elem><id_resource>37</id_resource></resource_list_elem><resource_list_elem><id_resource>52</id_resource></resource_list_elem><resource_list_elem><id_resource>53</id_resource></resource_list_elem><resource_list_elem><id_resource>54</id_resource></resource_list_elem><resource_list_elem><id_resource>55</id_resource></resource_list_elem><resource_list_elem><id_resource>56</id_resource></resource_list_elem><resource_list_elem><id_resource>57</id_resource></resource_list_elem><resource_list_elem><id_resource>58</id_resource></resource_list_elem><resource_list_elem><id_resource>59</id_resource></resource_list_elem><resource_list_elem><id_resource>60</id_resource></resource_list_elem><resource_list_elem><id_resource>61</id_resource></resource_list_elem><resource_list_elem><id_resource>62</id_resource></resource_list_elem><resource_list_elem><id_resource>63</id_resource></resource_list_elem><resource_list_elem><id_resource>64</id_resource></resource_list_elem><resource_list_elem><id_resource>14</id_resource></resource_list_elem></path><path><id_path>307</id_path><resource_list_elem><id_resource>24</id_resource></resource_list_elem><resource_list_elem><id_resource>25</id_resource></resource_list_elem><resource_list_elem><id_resource>26</id_resource></resource_list_elem><resource_list_elem><id_resource>27</id_resource></resource_list_elem><resource_list_elem><id_resource>28</id_resource></resource_list_elem><resource_list_elem><id_resource>29</id_resource></resource_list_elem><resource_list_elem><id_resource>30</id_resource></resource_list_elem><resource_list_elem><id_resource>31</id_resource></resource_list_elem><resource_list_elem><id_resource>32</id_resource></resource_list_elem><resource_list_elem><id_resource>33</id_resource></resource_list_elem><resource_list_elem><id_resource>34</id_resource></resource_list_elem><resource_list_elem><id_resource>35</id_resource></resource_list_elem><resource_list_elem><id_resource>36</id_resource></resource_list_elem><resource_list_elem><id_resource>37</id_resource></resource_list_elem><resource_list_elem><id_resource>38</id_resource></resource_list_elem><resource_list_elem><id_resource>39</id_resource></resource_list_elem><resource_list_elem><id_resource>40</id_resource></resource_list_elem><resource_list_elem><id_resource>41</id_resource></resource_list_elem><resource_list_elem><id_resource>65</id_resource></resource_list_elem><resource_list_elem><id_resource>15</id_resource></resource_list_elem><resource_list_elem><id_resource>16</id_resource></resource_list_elem><resource_list_elem><id_resource>17</id_resource></resource_list_elem><resource_list_elem><id_resource>18</id_resource></resource_list_elem><resource_list_elem><id_resource>19</id_resource></resource_list_elem><resource_list_elem><id_resource>20</id_resource></resource_list_elem><resource_list_elem><id_resource>21</id_resource></resource_list_elem><resource_list_elem><id_resource>22</id_resource></resource_list_elem><resource_list_elem><id_resource>23</id_resource></resource_list_elem><resource_list_elem><id_resource>43</id_resource></resource_list_elem><resource_list_elem><id_resource>44</id_resource></resource_list_elem><resource_list_elem><id_resource>45</id_resource></resource_list_elem><resource_list_elem><id_resource>46</id_resource></resource_list_elem><resource_list_elem><id_resource>14</id_resource></resource_list_elem></path><path><id_path>296</id_path><resource_list_elem><id_resource>5</id_resource></resource_list_elem><resource_list_elem><id_resource>6</id_resource></resource_list_elem><resource_list_elem><id_resource>7</id_resource></resource_list_elem><resource_list_elem><id_resource>8</id_resource></resource_list_elem><resource_list_elem><id_resource>9</id_resource></resource_list_elem><resource_list_elem><id_resource>10</id_resource></resource_list_elem><resource_list_elem><id_resource>11</id_resource></resource_list_elem><resource_list_elem><id_resource>12</id_resource></resource_list_elem><resource_list_elem><id_resource>13</id_resource></resource_list_elem><resource_list_elem><id_resource>14</id_resource></resource_list_elem></path><path><id_path>341</id_path><resource_list_elem><id_resource>1</id_resource></resource_list_elem><resource_list_elem><id_resource>2</id_resource></resource_list_elem><resource_list_elem><id_resource>3</id_resource></resource_list_elem><resource_list_elem><id_resource>4</id_resource></resource_list_elem><resource_list_elem><id_resource>5</id_resource></resource_list_elem><resource_list_elem><id_resource>6</id_resource></resource_list_elem><resource_list_elem><id_resource>7</id_resource></resource_list_elem><resource_list_elem><id_resource>8</id_resource></resource_list_elem><resource_list_elem><id_resource>9</id_resource></resource_list_elem><resource_list_elem><id_resource>10</id_resource></resource_list_elem><resource_list_elem><id_resource>11</id_resource></resource_list_elem><resource_list_elem><id_resource>12</id_resource></resource_list_elem><resource_list_elem><id_resource>13</id_resource></resource_list_elem><resource_list_elem><id_resource>47</id_resource></resource_list_elem><resource_list_elem><id_resource>48</id_resource></resource_list_elem><resource_list_elem><id_resource>49</id_resource></resource_list_elem><resource_list_ele