<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl"  href="aeroscheduling_input.xsl"?>
<!DOCTYPE root [
	<!ELEMENT root (resource+, path*, time_point*, time_profile*, routed_job*, job*, job_op*, setup_removal_table*, machine*, platform*, connection*)>
	<!ELEMENT resource (id_resource, name, resource_type, info1*, info2*)>
	<!ELEMENT id_resource (#PCDATA)>
	<!ELEMENT resource_type (#PCDATA)>
	<!ELEMENT info1 (#PCDATA)>
	<!ELEMENT info2 (#PCDATA)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT path (id_path, resource_list_elem+)>
	<!ELEMENT resource_list_elem (id_resource)>
	<!ELEMENT id_path (#PCDATA)>
	<!ELEMENT time_point (id_time_point, processing_time*, perishability_time*,release_no_timeshift*, release_time*, due_date_no_timeshift*, due_date_time*, deadline_no_timeshift*, deadline_time*, weight_obj*, setup_time*, removal_time*, dependent_setup_type*, dependent_removal_type*)>
	<!ELEMENT id_time_point (#PCDATA)>
	<!ELEMENT processing_time (#PCDATA)>
	<!ELEMENT perishability_time (#PCDATA)>
	<!ELEMENT release_no_timeshift (#PCDATA)>
	<!ELEMENT release_time (#PCDATA)>
	<!ELEMENT due_date_no_timeshift (#PCDATA)>
	<!ELEMENT due_date_time (#PCDATA)>
	<!ELEMENT deadline_no_timeshift (#PCDATA)>
	<!ELEMENT deadline_time (#PCDATA)>
	<!ELEMENT weight_obj (#PCDATA)>
	<!ELEMENT setup_time (#PCDATA)>
	<!ELEMENT removal_time (#PCDATA)>
	<!ELEMENT dependent_setup_type (#PCDATA)>
	<!ELEMENT dependent_removal_type (#PCDATA)>
	<!ELEMENT time_profile (id_time_profile, id_path, time_point_list_elem+)>
	<!ELEMENT time_point_list_elem (id_time_point)>
	<!ELEMENT id_time_profile (#PCDATA)>
	<!ELEMENT job (id_job, name, routed_job_list_elem+, multiple_routings_list_elem+)>
	<!ELEMENT routed_job (id_routed_job, job_type, time_shift, id_time_profile, weight_obj*)>
	<!ELEMENT routed_job_list_elem (id_routed_job)>
    <!ELEMENT multiple_routings_list_elem (id_resource, time_profile_list_elem+)>
    <!ELEMENT time_profile_list_elem (id_time_profile)>
	<!ELEMENT id_job (#PCDATA)>
	<!ELEMENT id_routed_job (#PCDATA)>
	<!ELEMENT job_type (#PCDATA)>
	<!ELEMENT time_shift (#PCDATA)>
	<!ELEMENT job_op (id_job, operation+)>
	<!ELEMENT operation (id_resource, time_point)>
	<!ELEMENT setup_removal_table (table_entry+)>
	<!ELEMENT table_entry (dependent_type1, dependent_type2,  setup_removal_type, dependent_time)>
	<!ELEMENT dependent_type1 (#PCDATA)>
	<!ELEMENT dependent_type2 (#PCDATA)>
	<!ELEMENT setup_removal_type (#PCDATA)>
	<!ELEMENT dependent_time (#PCDATA)>
	<!ELEMENT machine (resource_list_elem+)>
	<!ELEMENT platform (resource_list_elem+)>
	<!ELEMENT connection (id_job_from, id_resource_from, id_job_to, id_resource_to, connection_weight, connection_price, is_passenger)>
	<!ELEMENT id_job_from (#PCDATA)>
	<!ELEMENT id_resource_from (#PCDATA)>
	<!ELEMENT id_job_to (#PCDATA)>
	<!ELEMENT id_resource_to (#PCDATA)>
	<!ELEMENT connection_weight (#PCDATA)>
	<!ELEMENT connection_price (#PCDATA)>
	<!ELEMENT is_passenger (#PCDATA)>
]>
<root>
<resource>
	<id_resource>1</id_resource>
	<name>resource_1</name>
	<resource_type>blocking</resource_type>
</resource>
<resource>
    <id_resource>21</id_resource>
    <name>resource_21</name>
    <resource_type>blocking</resource_type>
</resource>
<resource>
    <id_resource>22</id_resource>
    <name>resource_22</name>
    <resource_type>blocking</resource_type>
</resource>
<resource>
	<id_resource>2</id_resource>
	<name>resource_2</name>
	<resource_type>dummy</resource_type>
</resource>
<resource>
	<id_resource>3</id_resource>
	<name>resource_3</name>
	<resource_type>blocking</resource_type>
</resource>
<resource>
    <id_resource>4</id_resource>
    <name>resource_4</name>
    <resource_type>blocking</resource_type>
</resource>
<resource>
    <id_resource>5</id_resource>
    <name>resource_5</name>
    <resource_type>blocking</resource_type>
</resource>
<resource>
    <id_resource>6</id_resource>
    <name>resource_6</name>
    <resource_type>blocking</resource_type>
</resource>
<resource>
    <id_resource>7</id_resource>
    <name>resource_7</name>
    <resource_type>blocking</resource_type>
</resource>
<resource>
    <id_resource>8</id_resource>
    <name>resource_8</name>
    <resource_type>dummy</resource_type>
</resource>
<resource>
    <id_resource>9</id_resource>
    <name>resource_9</name>
    <resource_type>multiple_routings</resource_type>
</resource>
<resource>
    <id_resource>10</id_resource>
    <name>resource_10</name>
    <resource_type>multiple_routings</resource_type>
</resource>
<path>
    <id_path>1</id_path>
    <resource_list_elem>
        <id_resource>1</id_resource>
    </resource_list_elem>
    <resource_list_elem>
        <id_resource>9</id_resource>
    </resource_list_elem>
    <resource_list_elem>
        <id_resource>3</id_resource>
    </resource_list_elem>
    <resource_list_elem>
        <id_resource>10</id_resource>
    </resource_list_elem>
    <resource_list_elem>
        <id_resource>5</id_resource>
    </resource_list_elem>
</path>
<path>
    <id_path>3</id_path>
    <resource_list_elem>
        <id_resource>5</id_resource>
    </resource_list_elem>
    <resource_list_elem>
        <id_resource>10</id_resource>
    </resource_list_elem>
    <resource_list_elem>
        <id_resource>3</id_resource>
    </resource_list_elem>
    <resource_list_elem>
        <id_resource>9</id_resource>
    </resource_list_elem>
    <resource_list_elem>
        <id_resource>1</id_resource>
    </resource_list_elem>
</path>
<path>
    <id_path>2</id_path>
    <resource_list_elem>
        <id_resource>9</id_resource>
    </resource_list_elem>
    <resource_list_elem>
        <id_resource>3</id_resource>
    </resource_list_elem>
    <resource_list_elem>
        <id_resource>10</id_resource>
    </resource_list_elem>
    <resource_list_elem>
        <id_resource>5</id_resource>
    </resource_list_elem>
</path>
<path>
    <id_path>4</id_path>
    <resource_list_elem>
        <id_resource>5</id_resource>
    </resource_list_elem>
    <resource_list_elem>
        <id_resource>10</id_resource>
    </resource_list_elem>
    <resource_list_elem>
        <id_resource>3</id_resource>
    </resource_list_elem>
    <resource_list_elem>
        <id_resource>9</id_resource>
    </resource_list_elem>
</path>


<path>
    <id_path>921</id_path>
    <resource_list_elem>
        <id_resource>21</id_resource>
    </resource_list_elem>
    <resource_list_elem>
        <id_resource>2</id_resource>
    </resource_list_elem>
    <resource_list_elem>
        <id_resource>22</id_resource>
    </resource_list_elem>
</path>
<path>
    <id_path>922</id_path>
    <resource_list_elem>
        <id_resource>22</id_resource>
    </resource_list_elem>
    <resource_list_elem>
        <id_resource>2</id_resource>
    </resource_list_elem>
    <resource_list_elem>
        <id_resource>21</id_resource>
    </resource_list_elem>
</path>
<path>
    <id_path>98</id_path>
    <resource_list_elem>
        <id_resource>8</id_resource>
    </resource_list_elem>
</path>

<path>
    <id_path>97</id_path>
    <resource_list_elem>
        <id_resource>7</id_resource>
    </resource_list_elem>
</path>

<path>
    <id_path>104</id_path>
    <resource_list_elem>
        <id_resource>4</id_resource>
    </resource_list_elem>
</path>

<path>
    <id_path>106</id_path>
    <resource_list_elem>
        <id_resource>6</id_resource>
    </resource_list_elem>
</path>

<time_point>
	<id_time_point>10001</id_time_point>
	<processing_time>15</processing_time>
	<release_no_timeshift>0</release_no_timeshift>
	<due_date_no_timeshift>0</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
	<id_time_point>10009</id_time_point>
	<processing_time>65</processing_time>
    <due_date_no_timeshift>70</due_date_no_timeshift>
	<dependent_setup_type>4</dependent_setup_type>
	<dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>10003</id_time_point>
    <processing_time>63</processing_time>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
	<id_time_point>100010</id_time_point>
	<processing_time>80</processing_time>
    <due_date_no_timeshift>253</due_date_no_timeshift>
	<dependent_setup_type>4</dependent_setup_type>
	<dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
	<id_time_point>10005</id_time_point>
	<processing_time>133</processing_time>
    <due_date_no_timeshift>333</due_date_no_timeshift>
	<dependent_setup_type>4</dependent_setup_type>
	<dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>100021</id_time_point>
    <processing_time>40</processing_time>
    <due_date_no_timeshift>70</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>10002</id_time_point>
    <processing_time>40</processing_time>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>100022</id_time_point>
    <processing_time>40</processing_time>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>10008</id_time_point>
    <processing_time>120</processing_time>
    <due_date_no_timeshift>70</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>10007</id_time_point>
    <processing_time>65</processing_time>
    <due_date_no_timeshift>70</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>10004</id_time_point>
    <processing_time>80</processing_time>
    <due_date_no_timeshift>253</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>10006</id_time_point>
    <processing_time>80</processing_time>
    <due_date_no_timeshift>253</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>



<time_point>
    <id_time_point>20009</id_time_point>
    <processing_time>65</processing_time>
    <release_no_timeshift>70</release_no_timeshift>
    <due_date_no_timeshift>130</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>20003</id_time_point>
    <processing_time>63</processing_time>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>200010</id_time_point>
    <processing_time>80</processing_time>
    <due_date_no_timeshift>313</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>20005</id_time_point>
    <processing_time>133</processing_time>
    <due_date_no_timeshift>393</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>200021</id_time_point>
    <processing_time>40</processing_time>
    <release_no_timeshift>70</release_no_timeshift>
    <due_date_no_timeshift>130</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>20002</id_time_point>
    <processing_time>40</processing_time>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>200022</id_time_point>
    <processing_time>40</processing_time>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>20008</id_time_point>
    <processing_time>120</processing_time>
    <release_no_timeshift>70</release_no_timeshift>
    <due_date_no_timeshift>130</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>20007</id_time_point>
    <processing_time>65</processing_time>
    <release_no_timeshift>70</release_no_timeshift>
    <due_date_no_timeshift>130</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>20004</id_time_point>
    <processing_time>80</processing_time>
    <due_date_no_timeshift>333</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>20006</id_time_point>
    <processing_time>80</processing_time>
    <due_date_no_timeshift>333</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>



<time_point>
    <id_time_point>30001</id_time_point>
    <processing_time>15</processing_time>
    <due_date_no_timeshift>396</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>30009</id_time_point>
    <processing_time>65</processing_time>
    <due_date_no_timeshift>276</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>30003</id_time_point>
    <processing_time>63</processing_time>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>300010</id_time_point>
    <processing_time>80</processing_time>
    <due_date_no_timeshift>133</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>30005</id_time_point>
    <processing_time>133</processing_time>
    <release_no_timeshift>0</release_no_timeshift>
    <due_date_no_timeshift>0</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>300021</id_time_point>
    <processing_time>40</processing_time>
    <due_date_no_timeshift>276</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>30002</id_time_point>
    <processing_time>40</processing_time>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>300022</id_time_point>
    <processing_time>40</processing_time>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>30008</id_time_point>
    <processing_time>120</processing_time>
    <due_date_no_timeshift>276</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>30007</id_time_point>
    <processing_time>65</processing_time>
    <due_date_no_timeshift>276</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>30004</id_time_point>
    <processing_time>80</processing_time>
    <due_date_no_timeshift>133</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>30006</id_time_point>
    <processing_time>80</processing_time>
    <due_date_no_timeshift>133</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>



<time_point>
    <id_time_point>40009</id_time_point>
    <processing_time>65</processing_time>
    <due_date_no_timeshift>326</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>40003</id_time_point>
    <processing_time>63</processing_time>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>400010</id_time_point>
    <processing_time>80</processing_time>
    <due_date_no_timeshift>183</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>40005</id_time_point>
    <processing_time>133</processing_time>
    <release_no_timeshift>50</release_no_timeshift>
    <due_date_no_timeshift>50</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>400021</id_time_point>
    <processing_time>40</processing_time>
    <due_date_no_timeshift>326</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>40002</id_time_point>
    <processing_time>40</processing_time>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>400022</id_time_point>
    <processing_time>40</processing_time>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>40008</id_time_point>
    <processing_time>120</processing_time>
    <due_date_no_timeshift>326</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>40007</id_time_point>
    <processing_time>65</processing_time>
    <due_date_no_timeshift>326</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>40004</id_time_point>
    <processing_time>80</processing_time>
    <due_date_no_timeshift>183</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>
<time_point>
    <id_time_point>40006</id_time_point>
    <processing_time>80</processing_time>
    <due_date_no_timeshift>183</due_date_no_timeshift>
    <dependent_setup_type>4</dependent_setup_type>
    <dependent_removal_type>4</dependent_removal_type>
</time_point>




<time_profile>
	<id_time_profile>101</id_time_profile>
	<id_path>1</id_path>
	<time_point_list_elem>
		<id_time_point>10001</id_time_point>
	</time_point_list_elem>
	<time_point_list_elem>
		<id_time_point>10009</id_time_point>
	</time_point_list_elem>
	<time_point_list_elem>
		<id_time_point>10003</id_time_point>
	</time_point_list_elem>
	<time_point_list_elem>
		<id_time_point>100010</id_time_point>
	</time_point_list_elem>
	<time_point_list_elem>
		<id_time_point>10005</id_time_point>
	</time_point_list_elem>
</time_profile>
<time_profile>
	<id_time_profile>201</id_time_profile>
	<id_path>2</id_path>
	<time_point_list_elem>
		<id_time_point>20009</id_time_point>
	</time_point_list_elem>
    <time_point_list_elem>
        <id_time_point>20003</id_time_point>
    </time_point_list_elem>
	<time_point_list_elem>
		<id_time_point>200010</id_time_point>
	</time_point_list_elem>
	<time_point_list_elem>
		<id_time_point>20005</id_time_point>
	</time_point_list_elem>
</time_profile>
<time_profile>
    <id_time_profile>301</id_time_profile>
    <id_path>3</id_path>
    <time_point_list_elem>
        <id_time_point>30005</id_time_point>
    </time_point_list_elem>
    <time_point_list_elem>
        <id_time_point>300010</id_time_point>
    </time_point_list_elem>
    <time_point_list_elem>
        <id_time_point>30003</id_time_point>
    </time_point_list_elem>
    <time_point_list_elem>
        <id_time_point>30009</id_time_point>
    </time_point_list_elem>
    <time_point_list_elem>
        <id_time_point>30001</id_time_point>
    </time_point_list_elem>
</time_profile>
<time_profile>
    <id_time_profile>401</id_time_profile>
    <id_path>4</id_path>
    <time_point_list_elem>
        <id_time_point>40005</id_time_point>
    </time_point_list_elem>
    <time_point_list_elem>
        <id_time_point>400010</id_time_point>
    </time_point_list_elem>
    <time_point_list_elem>
        <id_time_point>40003</id_time_point>
    </time_point_list_elem>
    <time_point_list_elem>
        <id_time_point>40009</id_time_point>
    </time_point_list_elem>
</time_profile>

<time_profile>
    <id_time_profile>102</id_time_profile>
    <id_path>921</id_path>
    <time_point_list_elem>
        <id_time_point>100021</id_time_point>
    </time_point_list_elem>
    <time_point_list_elem>
        <id_time_point>10002</id_time_point>
    </time_point_list_elem>
    <time_point_list_elem>
        <id_time_point>100022</id_time_point>
    </time_point_list_elem>
 </time_profile>
<time_profile>
    <id_time_profile>202</id_time_profile>
    <id_path>921</id_path>
    <time_point_list_elem>
        <id_time_point>200021</id_time_point>
    </time_point_list_elem>
    <time_point_list_elem>
        <id_time_point>20002</id_time_point>
    </time_point_list_elem>
    <time_point_list_elem>
        <id_time_point>200022</id_time_point>
    </time_point_list_elem>
</time_profile>
<time_profile>
    <id_time_profile>302</id_time_profile>
    <id_path>922</id_path>
    <time_point_list_elem>
        <id_time_point>300022</id_time_point>
    </time_point_list_elem>
    <time_point_list_elem>
        <id_time_point>30002</id_time_point>
    </time_point_list_elem>
    <time_point_list_elem>
        <id_time_point>300021</id_time_point>
    </time_point_list_elem>
</time_profile>
<time_profile>
    <id_time_profile>402</id_time_profile>
    <id_path>922</id_path>
    <time_point_list_elem>
        <id_time_point>400022</id_time_point>
    </time_point_list_elem>
    <time_point_list_elem>
        <id_time_point>40002</id_time_point>
    </time_point_list_elem>
    <time_point_list_elem>
        <id_time_point>400021</id_time_point>
    </time_point_list_elem>
</time_profile>

<time_profile>
    <id_time_profile>108</id_time_profile>
    <id_path>98</id_path>
    <time_point_list_elem>
        <id_time_point>10008</id_time_point>
    </time_point_list_elem>
</time_profile>
<time_profile>
    <id_time_profile>208</id_time_profile>
    <id_path>98</id_path>
    <time_point_list_elem>
        <id_time_point>20008</id_time_point>
    </time_point_list_elem>
</time_profile>
<time_profile>
    <id_time_profile>308</id_time_profile>
    <id_path>98</id_path>
    <time_point_list_elem>
        <id_time_point>30008</id_time_point>
    </time_point_list_elem>
</time_profile>
<time_profile>
    <id_time_profile>408</id_time_profile>
    <id_path>98</id_path>
    <time_point_list_elem>
        <id_time_point>40008</id_time_point>
    </time_point_list_elem>
</time_profile>

<time_profile>
    <id_time_profile>107</id_time_profile>
    <id_path>97</id_path>
    <time_point_list_elem>
        <id_time_point>10007</id_time_point>
    </time_point_list_elem>
</time_profile>
<time_profile>
    <id_time_profile>207</id_time_profile>
    <id_path>97</id_path>
    <time_point_list_elem>
        <id_time_point>20007</id_time_point>
    </time_point_list_elem>
</time_profile>
<time_profile>
    <id_time_profile>307</id_time_profile>
    <id_path>97</id_path>
    <time_point_list_elem>
        <id_time_point>30007</id_time_point>
    </time_point_list_elem>
</time_profile>
<time_profile>
    <id_time_profile>407</id_time_profile>
    <id_path>97</id_path>
    <time_point_list_elem>
        <id_time_point>40007</id_time_point>
    </time_point_list_elem>
</time_profile>



<time_profile>
    <id_time_profile>104</id_time_profile>
    <id_path>104</id_path>
    <time_point_list_elem>
        <id_time_point>10004</id_time_point>
    </time_point_list_elem>
</time_profile>
<time_profile>
    <id_time_profile>204</id_time_profile>
    <id_path>104</id_path>
    <time_point_list_elem>
        <id_time_point>20004</id_time_point>
    </time_point_list_elem>
</time_profile>
<time_profile>
    <id_time_profile>304</id_time_profile>
    <id_path>104</id_path>
    <time_point_list_elem>
        <id_time_point>30004</id_time_point>
    </time_point_list_elem>
</time_profile>
<time_profile>
    <id_time_profile>404</id_time_profile>
    <id_path>104</id_path>
    <time_point_list_elem>
        <id_time_point>40004</id_time_point>
    </time_point_list_elem>
</time_profile>

<time_profile>
    <id_time_profile>106</id_time_profile>
    <id_path>106</id_path>
    <time_point_list_elem>
        <id_time_point>10006</id_time_point>
    </time_point_list_elem>
</time_profile>
<time_profile>
    <id_time_profile>206</id_time_profile>
    <id_path>106</id_path>
    <time_point_list_elem>
        <id_time_point>20006</id_time_point>
    </time_point_list_elem>
</time_profile>
<time_profile>
    <id_time_profile>306</id_time_profile>
    <id_path>106</id_path>
    <time_point_list_elem>
        <id_time_point>30006</id_time_point>
    </time_point_list_elem>
</time_profile>
<time_profile>
    <id_time_profile>406</id_time_profile>
    <id_path>106</id_path>
    <time_point_list_elem>
        <id_time_point>40006</id_time_point>
    </time_point_list_elem>
</time_profile>


<routed_job>
	<id_routed_job>101</id_routed_job>
	<job_type>normal_job</job_type>
	<time_shift>0</time_shift>
	<id_time_profile>101</id_time_profile>
</routed_job>
<routed_job>
	<id_routed_job>201</id_routed_job>
	<job_type>normal_job</job_type>
	<time_shift>0</time_shift>
	<id_time_profile>201</id_time_profile>
</routed_job>
<routed_job>
	<id_routed_job>301</id_routed_job>
	<job_type>normal_job</job_type>
	<time_shift>0</time_shift>
	<id_time_profile>301</id_time_profile>
</routed_job>
<routed_job>
	<id_routed_job>401</id_routed_job>
	<job_type>normal_job</job_type>
	<time_shift>0</time_shift>
	<id_time_profile>401</id_time_profile>
</routed_job>
<job>
    <id_job>1</id_job>
    <name>job_1</name>
    <routed_job_list_elem>
        <id_routed_job>101</id_routed_job>
    </routed_job_list_elem>
    <multiple_routings_list_elem>
        <id_resource>9</id_resource>
        <time_profile_list_elem>
            <id_time_profile>102</id_time_profile>
        </time_profile_list_elem>
        <time_profile_list_elem>
            <id_time_profile>108</id_time_profile>
        </time_profile_list_elem>
        <time_profile_list_elem>
            <id_time_profile>107</id_time_profile>
        </time_profile_list_elem>
    </multiple_routings_list_elem>
    <multiple_routings_list_elem>
        <id_resource>10</id_resource>
        <time_profile_list_elem>
            <id_time_profile>104</id_time_profile>
        </time_profile_list_elem>
        <time_profile_list_elem>
            <id_time_profile>106</id_time_profile>
        </time_profile_list_elem>
    </multiple_routings_list_elem>
</job>
<job>
    <id_job>2</id_job>
    <name>job_2</name>
    <routed_job_list_elem>
        <id_routed_job>201</id_routed_job>
    </routed_job_list_elem>
    <multiple_routings_list_elem>
        <id_resource>9</id_resource>
        <time_profile_list_elem>
            <id_time_profile>202</id_time_profile>
        </time_profile_list_elem>
        <time_profile_list_elem>
            <id_time_profile>208</id_time_profile>
        </time_profile_list_elem>
        <time_profile_list_elem>
            <id_time_profile>207</id_time_profile>
        </time_profile_list_elem>
    </multiple_routings_list_elem>
    <multiple_routings_list_elem>
        <id_resource>10</id_resource>
        <time_profile_list_elem>
            <id_time_profile>204</id_time_profile>
        </time_profile_list_elem>
        <time_profile_list_elem>
            <id_time_profile>206</id_time_profile>
        </time_profile_list_elem>
    </multiple_routings_list_elem>
</job>
<job>
    <id_job>3</id_job>
    <name>job_3</name>
    <routed_job_list_elem>